
from marshmallow import Schema, fields, validate
from decimal import ROUND_HALF_UP

class ProductSchema(Schema):
    """
    Marshmallow schema for validating and serializing product data.
    """
    id = fields.Str(dump_only=True)
    # product_code is generated by the system, so it should be read-only.
    product_code = fields.Str(dump_only=True)
    name = fields.Str(
        required=True,
        validate=validate.Length(min=2, error="Product name must be at least 2 characters long.")
    )
    description = fields.Str(required=False, allow_none=True) # Description can be optional
    price = fields.Decimal(
        required=True,
        validate=validate.Range(min=0, error="Price must be a non-negative number."),
        places=2,  # Quantize to 2 decimal places on load.
        rounding=ROUND_HALF_UP # Use standard rounding.
    )
    stock = fields.Int(
        required=True,
        validate=validate.Range(min=0, error="Stock must be a non-negative integer.")
    )
    created_at = fields.DateTime(format='%Y-%m-%dT%H:%M:%S', dump_only=True)
    updated_at = fields.DateTime(format='%Y-%m-%dT%H:%M:%S', dump_only=True)
